global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'student-monitoring'



scrape_configs:
  # Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL
  - job_name: 'postgresql'
    static_configs:
      - targets: ['localhost:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'my_postgresql_db'

  # System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'my_laptop'

  # Custom API exporter
  - job_name: 'custom_api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'external_apis'
